---
# Playbook group_vars
#
# We put platform-wide variables here. Keep in mind ansible variable
# precedence[1]. To override values here, you need to use a specific inventory
# group_vars file e.g. inventory/group_vars/catalog/vars.yml. These variables
# take precedence over inventory/group_vars/all.
#
# [1]: https://docs.ansible.com/ansible/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable


# apache2 role
apache2_ssl_certificate_file: "{{ default_tls_host_certificate_filepath }}"
apache2_ssl_certificate_key_file: "{{ default_tls_host_key_filepath }}"


# common roles
common_tls_host_key: "{{ default_tls_host_key }}"
common_tls_host_certificate: "{{ default_tls_host_certificate }}"


# site-wide datagov variables
datagov_support_email: datagov@gsa.gov
datagov_team_email: datagovhelp@gsa.gov


# Data.gov defaults
default_jumpbox_operators: "{{ vault_default_jumpbox_operators }}"
# Default TLS/SSL certificate used for internal traffic to host.
default_tls_host_certificate_filepath: /etc/ssl/certs/datagov_host.crt
default_tls_host_key_filepath: /etc/ssl/private/datagov_host.key


# This should probably be environment specific
jumpbox_operators: "{{ default_jumpbox_operators }}"


# newrelic monitoring
nrinfragent_config:
  license_key: "{{ vault_nrinfragent_license_key }}"
  custom_attributes:
    environment: "{{ datagov_environment | default('unknown') }}"
    service: "{{ datagov_service | default('unknown') }}"


# Nginx
nginx_remove_default_vhost: true
nginx_ppa_use: true
nginx_ppa_version: stable
nginx_extra_conf_options: |-
  include /etc/nginx/modules-enabled/*.conf;


# PHP-FPM
php_enable_php_fpm: true
php_webserver_daemon: nginx


# new python version
python_version_number: 2.7.10
python_version_name: Python-{{ python_version_number }}
python_version_url: https://www.python.org/ftp/python/{{ python_version_number}}/{{ python_version_name }}.tgz
python_version_directory: /usr/local/lib/python{{ python_version_number }}
python_home: "{{ python_version_directory }}"


# Disabling MySQL server (we need only client on this machine)
mysql_enabled_on_startup: false


# PHP
php_memory_limit: 512M
php_expose_php: 0
php_fpm_pm_max_children: 200
php_fpm_pm_start_servers: 15
php_fpm_pm_min_spare_servers: 5
php_fpm_pm_max_spare_servers: 20
php_fpm_request_terminate_timeout: 30s
php_opcache_conf_filename: "10-opcache.ini"
