- name: restart redis
  service: name=redis-server state=restarted

- name: reload supervisor
  command: supervisorctl reread
  tags:
    - skip_ansible_lint

- name: restart tomcat
  service: name={{ catalog_harvester_tomcat_service }} state=restarted
