---
datagov_sandbox_env: ci

default_tls_host_key: "{{ vault_default_tls_host_key }}"
default_tls_host_certificate: |-
  -----BEGIN CERTIFICATE-----
  MIIEVTCCAz2gAwIBAgIJALhe8ZrGe78rMA0GCSqGSIb3DQEBCwUAMIHAMQswCQYD
  VQQGEwJVUzELMAkGA1UECAwCREMxEzARBgNVBAcMCldhc2hpbmd0b24xKDAmBgNV
  BAoMH0dlbmVyYWwgU2VydmljZXMgQWRtaW5pc3RyYXRpb24xKjAoBgNVBAsMIVRl
  Y2hub2xvZ3kgVHJhbnNmb3JtYXRpb24gU2VydmljZTEVMBMGA1UEAwwMKi5kYXRh
  Z292LnVzMSIwIAYJKoZIhvcNAQkBFhNkYXRhZ292aGVscEBnc2EuZ292MB4XDTE5
  MDIwOTAwMjMzNloXDTIxMDIwODAwMjMzNlowgcAxCzAJBgNVBAYTAlVTMQswCQYD
  VQQIDAJEQzETMBEGA1UEBwwKV2FzaGluZ3RvbjEoMCYGA1UECgwfR2VuZXJhbCBT
  ZXJ2aWNlcyBBZG1pbmlzdHJhdGlvbjEqMCgGA1UECwwhVGVjaG5vbG9neSBUcmFu
  c2Zvcm1hdGlvbiBTZXJ2aWNlMRUwEwYDVQQDDAwqLmRhdGFnb3YudXMxIjAgBgkq
  hkiG9w0BCQEWE2RhdGFnb3ZoZWxwQGdzYS5nb3YwggEiMA0GCSqGSIb3DQEBAQUA
  A4IBDwAwggEKAoIBAQCrvX1zkUtZyxjkniG8x8EXoFHmtm2PiavFhcs6d0W2IHPe
  jXXLUEXJb7ldwdKwi5yCTuW8J0CGoIl8EkkTy3+rQWjjS74iTvewxkcYVdHB/oXf
  wpPuL9azvX1WEekfdKCYf98D+RWnr+5XWMbXyRafI2a9yeE3et6mkeqeu4iP/8iA
  G7o/BEcLhrDFQFuzA0WQxGhajqQvSTTfjhEp2Dqq4u/Ek7DqVuf7IJ/KYt3PeGeX
  bV19LAzKt2HE5uqXSRZn0vnMRyCT9kz+yNZqUVHCzk7GE01Jl7wxTDU1cGraqrMK
  9Cg4zBNX1g3B8xucGOichpawOBiW+a5A2yhCNPzjAgMBAAGjUDBOMB0GA1UdDgQW
  BBRe5bzhJ9N8pjtAXKbwzLu6c2F4hDAfBgNVHSMEGDAWgBRe5bzhJ9N8pjtAXKbw
  zLu6c2F4hDAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQCdv74tZfxn
  NsfDG4SwnPvusMorYWM719wDdfXO0VIQMGcP/aRitgw6aMlHXpWltqMXOO0NyOv3
  zMbYIvTNJWRCFiOMSUSTc3UEs/Hd5/O8d31Ncqg7MJRfISlIRvjQ6FntOZ3WDmrG
  ZwnqGkfGYpj92Q2xuXDd7FjGTKXVJiwaVMkDifUe/ez74R3ltSNeohaLOkZf5Zcw
  68XH2jjigSenaTkHd8QND1yde5/ekyX7s594M5tz16Tr05Wmnf+3OSNFssooFlXY
  a6iApABZqU0Aac0KNKxx7F8BvcTfems78jd0RhKrGKD77l4VTtFb+gU2C02Abbm+
  lo4YdL0A8Y/f
  -----END CERTIFICATE-----


fluentd_disable: true
nessus_agent_disable: true
trendmicro_disable: true

# public urls
urls_public:
  catalog: https://catalog.{{ datagov_sandbox_env }}.datagov.us
urls_private:
  catalog: https://catalog.{{ datagov_sandbox_env }}.datagov.us

ckan_site_domain: "{{ urls_public.catalog }}"

# s3 bucket
catalog_bucket_name: "{{ vault_catalog_bucket_name }}"

# List of CodeIgniter pre-approved admin emails
codeigniter_pre_approved_admins: "{{ vault_codeigniter_pre_approved_admins }}"


# App environment
web_app_env: production
real_ansible_env: production


# newrelic
nrinfragent_license_key: "{{ vault_nrinfragent_license_key }}"


# postfix
postfix_relayhost: smtp.gsa.gov
postfix_relayhost_port: 25
postfix_sasl_auth_enable: false
postfix_relaytls: true
default_email_from: no-reply@data.gov
postfix_key: "{{ vault_postfix_key }}"
postfix_pem: "{{ vault_postfix_pem }}"


# SAML
saml2_idp_entry: login.test.max.gov
saml2_idp_metadata_url: "https://{{ saml2_idp_entry }}/idp/shibboleth"
saml_idp_cert_fprint: "67:76:BB:87:FE:76:D6:4A:BE:19:3F:E2:B6:1A:49:06:AE:56:06:B8"
saml2_sp_public_key: "{{ vault_saml2_sp_public_key }}"
saml2_sp_private_pem: "{{ vault_saml2_sp_private_pem }}"


# fgdc2iso service on catalog-harvester
# saxon license
saxon_license: "{{ vault_saxon_license }}"


# SecOps user
secops_user: "{{ vault_secops_user }}"
secops_user_public_key: "{{ vault_secops_user_public_key }}"


# solr
solr_master_server: datagovsolr1tf.internal.{{ datagov_sandbox_env }}.datagov.us
