---
# CRM prerequisites
- name: Copying CRM configuration for Nginx
  template:
    src: "crm.nginx.conf"
    dest: "/etc/nginx/sites-enabled/crm.nginx.conf"
  notify:
    - reload nginx

- name: Mkdir /var/www/
  file:
    path: "/var/www"
    state: directory
    owner: "www-data"
    group: "www-data"
    mode: 0777

- name: Copy SAML crt
  template:
    src: "mycert.pem"
    dest: "{{ saml_sp_cert_path }}"
    mode: 0644

- name: Copy SAML key
  template:
    src: "mykey.pem"
    dest: "{{ saml_sp_private_key_path }}"
    mode: 0644

- name: Installing required packages
  package: name={{ item }} state=present
  with_items:
    - mariadb-client-10.1
    - php{{ php_version }}-zip
    - nginx-extras

- name: Remove old rollback code
  file: path="{{ project_source_rollback_path }}" state=absent
