---
- name: set worker type
  set_fact:
    worker_type: "{{ hostvars[inventory_hostname]['usage'] | default('main_worker') }}"
  tags:
    - redis
    - fgdc2iso

- include: fgdc2iso.yml
  tags: ['fgdc2iso']
  when: worker_type == 'main_worker'

- include: redis.yml
  tags: ['redis']
  when: worker_type == 'main_worker'

- name: Remove pip installed supervisor
  pip: name=supervisor virtualenv=/usr/lib/ckan/ state=absent

- name: remove supervisor.conf init
  file: dest=/etc/init/supervisor.conf state=absent

- name: install supervisor
  apt: name=supervisor state=present

- name: copy supervisord config
  copy: src=etc/supervisord_{{ worker_type }}.conf dest=/etc/supervisord/conf.d/harvest.conf
  notify: reload supervisor

- name: enable supervisor service
  service: name=supervisor state=started enabled=yes

- name: remove supervisor cron job
  file: dest=/etc/cron.d/supervisor state=absent

- name: copy worker cron job, if any
  copy: src=etc/cron.d/ckan_{{ worker_type }} dest=/etc/cron.d/ckan
  tags: ['cron']

- name: copy qa worker executables
  action: copy src={{item}} dest=/{{item}} mode=0744
  with_items:
    - usr/bin/celery-mem-check.sh
  when: worker_type == 'qa_worker'
