---
- name: Converge
  hosts: all
  roles:
    - role: geerlingguy.php
    - role: geerlingguy.nginx
    - role: geerlingguy.php-mysql
    - role: geerlingguy.php-memcached
    - role: geerlingguy.composer
    - role: wordpress

